### ISSUE TITLE
Improving block parts traced data

### ISSUE THREAD

**Issue by staheri14** [celestiaorg/celestia-core#1256]
Tracing stale block parts, i.e., those belonging to block heights older than the current round state of the receiving peer, can provide valuable insights. This process helps in understanding how well peers are updated about each other's states and the extent of unnecessary stale block part exchanges. Improving the exchange of state updates between peers could potentially minimize these redundant transmissions, hence the bandwidth utilization hence potentially the throughput. 

To achieve the above goal, the tracing data pertaining to block parts may require updates in terms of **the height and round of each traced block part**. This would facilitate easier comparison against the receiving peer's state, enabling the identification of stale parts. Moreover, the current tracing data fails to **differentiate between block parts exchanged during block synchronization** (when a peer is attempting to catch up) and those propagated **in real-time** under normal conditions. Recording this distinction as part of the traced data is also necessary.

**Comment by evan-forbes** [comment]
this is partially addressed in https://github.com/celestiaorg/celestia-core/pull/1292, where we distinguish between block parts for catchup and block parts gossiped during block prop.

> the tracing data pertaining to block parts may require updates in terms of the height and round of each traced block part

I'm guessing this means adding more data to the block part trace with the receiving node's current height/round? If so, in general I think it would be more ideal to piece this information together using the existing data instead of duplicating data collection.

I'm assigning myself to this as I think this falls under the network trace, where we can clearly see irrelevant or outdated block parts.

**Comment by staheri14** [comment]
Can you please elucidate on the parts of the current issue that are addressed in #1292, making it easier to track what are not covered yet.

**Comment by evan-forbes** [comment]
> Tracing stale block parts, i.e., those belonging to block heights older than the current round state of the receiving peer, can provide valuable insights

this part I think should be done after data has been collected instead of holding the mutex to read and then record the current step of consensus, since that's already being recorded

> differentiate between block parts exchanged during block synchronization (when a peer is attempting to catch up)

this is done in #1292 and the backports
