### ISSUE TITLE
CAT can return reserved txs

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-core#1266]
Occasionally, CAT will return txs that are reserved but not yet stored. This can result in weird behavior, such as passing the application a zero length transaction during PrepareProposal.

To fix this, we just need to filter out all reserved txs in the few occassions where they actually get read before actually being added or released.

**Comment by rootulp** [comment]
What is a reserved tx?

>  CAT will return txs that are reserved but not yet stored.

Stored where?

**Comment by rootulp** [comment]
Answering my questions from above:
- A reserved tx is a tx that has been received by the CAT Pool but hasn't been processed yet. Reserved txs aren't ready for inclusion in a block because they haven't gone through `CheckTx` yet. 
- I think "not yet stored" meant not yet stored in the mempool but that's kinda confusing because the tx _is_ in the mempool, it's just processing and not ready for inclusion in a block.

See https://github.com/celestiaorg/celestia-core/pull/1267#pullrequestreview-1944044341

**Comment by evan-forbes** [comment]
closing as completed
