### ISSUE TITLE
Prototype using QUIC instead of tcp and proprietary handshakes

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-core#1385]
While not technically purpose built for p2p applications, QUIC streams could replace our existing mechanisms for multiplexing messages and offer significant benefits. Besides removing multiple round trips per the handshake, QUIC also offers the ability to avoid HOL and to make use of more widely used (potentially more battle tested and debugged) software.

### AC

Create a prototype that uses QUIC instead of tcp and secret conn. Compare its high level performance (consensus throughput and peer drops) using our network tests and report them here.

**Comment by evan-forbes** [comment]
The only reason why we would want to prototype without using libp2p is to help debug the current issues in comet where we are unable to utilize all of the bandwidth with multiple nodes and latency.

tbc, the goal of this issue is not to write a proprietary p2p stack based on QUIC

**Comment by rach-id** [comment]
# Investigation setup

We added support for QUIC streams in tendermint here https://github.com/celestiaorg/celestia-core/pull/1466, using go-quic library. 

Then, to benchmark the performance, we implemented a mock reactor that floods the network with raw data and traces the data sent/received. This reactor was enabled both for the QUIC refactor: https://github.com/celestiaorg/celestia-core/tree/quic-bench-reactor and also the native tm stack: https://github.com/celestiaorg/celestia-core/tree/updating-the-mock-reactor-updated. 

Then, for better results, we disabled all the reactors except PEX so that the only data sent across the network is the mock reactor data.

After running the experiments, we noticed that the quic connections in the QUIC refactor hang after a while. So, to have more accurate results, we implemented a simple project https://github.com/rach-id/quic-bench that uses go-quic to create a QUIC network where each peer floods its peers with random data. This allowed benchmarking the QUIC performance without even the overhead added by tendermint, protobuf encoding/decoding, peers handling, etc.

To run the benchmarks, we used this branch of congest https://github.com/celestiaorg/congest/tree/tm-quic-benchmarks which creates a network of servers, provisions them, runs the network, then collects the logs.

The plots below were generated using the traces collected from the network using congest and processed using https://github.com/celestiaorg/traces_analysis.

The servers' setup:

- 52 validators distributed across the world. the plots below show the regions.
- For the QUIC benchmarks, we increased the udp buffers in all the servers:
```
sudo sysctl -w net.core.rmem_max=16777216
sudo sysctl -w net.core.wmem_max=16777216
sudo sysctl -w net.core.rmem_default=8388608
sudo sysctl -w net.core.wmem_default=8388608
sudo sysctl -w net.ipv4.udp_mem="8388608 8388608 16777216"
sudo sysctl -w net.ipv4.udp_rmem_min=1638400
sudo sysctl -w net.ipv4.udp_wmem_min=1638400
```
- For the tendermint native stack benchmarks, we used BBR + mptcp in all the servers:
```
# Load the BBR module
echo "Loading BBR module..."
modprobe tcp_bbr
# Verify if the BBR module is loaded
if lsmod | grep -q "tcp_bbr"; then
  echo "BBR module loaded successfully."
else
  echo "Failed to load BBR module."
  exit 1
fi
# Add BBR to the list of available congestion control algorithms
echo "Updating sysctl settings..."
sysctl -w net.core.default_qdisc=fq
sysctl -w net.ipv4.tcp_congestion_control=bbr

# Enable MPTCP
sysctl -w net.mptcp.enabled=1

# Set the path manager to ndiffports
sysctl -w net.mptcp.mptcp_path_manager=ndiffports

# Specify the number of subflows
SUBFLOWS=16
sysctl -w net.mptcp.mptcp_ndiffports=$SUBFLOWS
# Make the changes persistent across reboots
echo "Making changes persistent..."
echo "net.core.default_qdisc=fq" >> /etc/sysctl.conf
echo "net.ipv4.tcp_congestion_control=bbr" >> /etc/sysctl.conf
```

Also, we increase the send/receive rate to 100Gbps.

# Findings

After running the different networks for a few minutes, we collected the logs and generated the following plots.

## Native tendermint stack + BBR + mptcp

### Peer upload vs download average speed:

<img width="1414" alt="image" src="https://github.com/user-attachments/assets/ad329eda-e426-455a-863b-86ce1397ba34">

### Peer upload vs download progression:

<img width="1234" alt="image" src="https://github.com/user-attachments/assets/354f9c61-23b3-4111-b654-58826f548269">

### Region upload vs download average speed:

<img width="1409" alt="image" src="https://github.com/user-attachments/assets/bd67c416-8df1-4e33-8844-fee350507348">

## Tendermint stack QUIC refactor + large UDP buffers

### Peer upload vs download average speed:

<img width="1396" alt="image" src="https://github.com/user-attachments/assets/81dfbf73-89a9-4f5c-a615-a263d4cdb4c9">

### Peer upload vs download progression:

<img width="1122" alt="image" src="https://github.com/user-attachments/assets/ebd75114-a455-472a-8c7f-c35b62e72bae">

### Region upload vs download average speed:

<img width="1402" alt="image" src="https://github.com/user-attachments/assets/dd5e3b8b-342d-4f52-920d-f5f76aca8e5d">

## QUIC benchmark tool + large UDP buffers

### Peer upload vs download average speed:

<img width="1386" alt="image" src="https://github.com/user-attachments/assets/3bb6f0c3-be06-4bb7-9309-bcc74d479ace">

### Peer upload vs download progression:

<img width="1125" alt="image" src="https://github.com/user-attachments/assets/9a943092-6ffc-4730-909c-a6011c7e498c">

### Region upload vs download average speed:

<img width="1390" alt="image" src="https://github.com/user-attachments/assets/f3b8459a-2617-477a-9a59-c1363ba870b2">

# Insights

We can see in the plots that the QUIC benchmark tool yields better results than the Tendermint QUIC refactor. So we will use it as a reference for the QUIC performance instead of the QUIC refactor. The reason being is the QUIC refactor was still a WIP and thus the performance can still be improved. However, the QUIC benchmarking tool uses out of the box go-quic without any changes. This makes it a good reference for performance, as that's the best we can.

So, if we compare the QUIC benchmarking tool performance with the native tendermint stack + BBR, we see that in both the worst cases, where we have servers in far places in the world, sometimes in a different continent, and the best cases, where the servers are in the same site, the performance of the native tendermint stack + BBR is better, the bandwidth is better utilized.

# Conclusions

Given the above numbers, it seems more reasonable to keep the existing tendermint stack and pair it with BBR to have the best possible performance. Then, we will need to focus on improving the message passing mechanisms to be able to fully utilise the bandwidth. This will be tracked in this issue https://github.com/celestiaorg/celestia-core/issues/1531.

**Comment by rach-id** [comment]
# More insights: comparing different data sizes and streams in QUIC vs TCP + BBR +mptcp

The setups are the same as above.

## QUIC

### 500 bytes data in 4 streams

![image](https://github.com/user-attachments/assets/38efdd59-57fa-4a76-a68f-3e7c7bef595a)

### 5mb data in 4 streams

![image](https://github.com/user-attachments/assets/4ac37004-a7b6-4e0e-aa95-b13e9ed0da4f)

Note: when running the experiment, the CPU usage increases with the number of streams we're opening.

<details>
<summary>1 stream resources usage</summary>
![image](https://github.com/user-attachments/assets/9f071595-9a69-4a5e-920c-b2408488f23c)
</details>

<details>
<summary>256 stream resources usage</summary>
![image](https://github.com/user-attachments/assets/57abe877-6a28-4d60-b247-edac58f1f171)
</details>

<details>
<summary>opening a new stream every minute</summary>
![image](https://github.com/user-attachments/assets/6b2a1327-dc97-4c59-80d0-40359279db2f)
We see that after opening ~20-40 stream, QUIC keeps performing the same way. if we open <20 streams, the performance is best. This could also be due to the data being sent is increased with every stream.
</details>

## TCP + BBR + mptcp

### 500 bytes 

![image](https://github.com/user-attachments/assets/5c471d67-b887-4156-9e68-4363535e4003)

Apparently, the smaller the data being sent, the more performance we get from the comet's p2p stack.

### 5mb bytes

There is a memory leak apparently somewhere that makes the nodes OOM after a short while.

We will try to fix it in this issue <Add issue>
