### ISSUE TITLE
Refactor remaining changes to tendermint to be more isolated

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-core#505]
## Summary

Refactor modifications to our fork of tendermint to make pulling changes from upstream easier.

## Details

One of the goals of our recent decision to reduce the scope of the modifications to our fork of tendermint is to allow for easier pulling of changes from upstream. To further this goal, we should also refactor the remaining necessary changes so that they interfere with tendermint code as little as possible. This will likely mean decoupling existing methods from certain types, and possibly even moving them into their own packages.

### Action Items
- [ ] #524 
- [ ] refactor share and merge splitting 
### References

tracking issue #491 
ADR #504

**Comment by Wondertan** [comment]
@evan-forbes, I didn't check the ADR yet but as part of #296 and https://github.com/celestiaorg/celestia-node/issues/21 I want to extract DAHeader in a separate thing, so part of the issue is on me. If you remember I already did some work towards this in https://github.com/celestiaorg/celestia-core/pull/427.

**Comment by evan-forbes** [comment]
closed by the merging of #534
