### ISSUE TITLE
Validator appears on the exporer even after the server was stopped

### ISSUE THREAD

**Issue by cosminbg** [celestiaorg/celestia-core#619]
Validator appears as unbounded on https://celestia.observer/validators more than a week after the server was stopped. IMO it should refresh the list periodically

**Comment by liamsi** [comment]
That is because until a validator did not fully unbond they are still a validator and will be shown as one in the block explorer. This is intentional though the UI could probably be clearer on this a bit. The right place for this issue would rather be: https://github.com/forbole/big-dipper-2.0-cosmos

**Comment by cosminbg** [comment]
ok, got it. Thanks!
