### ISSUE TITLE
Add support for returning proofs for transactions larger than two shares

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-core#621]
Almost all standard transactions will be able to fit in two shares, currently 512 bytes, but it is possible to create a transaction that is larger than 512 bytes. If this occurs, then the current way we generate inclusion proofs (#615) for those txs will not handle them. This can be fixed by removing some arbitrary restrictions, along with changing the nmt API so that we can create inclusion proofs over a given range.

**Comment by evan-forbes** [comment]
This error pops up very often, and to make it much worse, the cli doesn't have a way to query without proving that a tx was committed to

**Comment by liamsi** [comment]
> along with changing the nmt API so that we can create inclusion proofs over a given range.

IIRC, the NMT supports range proofs. e.g. to prove a whole namespace range proofs are used: https://github.com/celestiaorg/nmt/blob/b43d67c6053773034b832c6539f90ed4962777b8/nmt.go#L185

The API just needs to be extended to use this for arbitrary ranges instead of only those for namespace start-end ranges.

**Comment by liamsi** [comment]
Is this all you need @evan-forbes ?
https://github.com/celestiaorg/nmt/pull/57

**Comment by evan-forbes** [comment]
yep, just the API change is needed
