### ISSUE TITLE
Updating to the latest Tendermint versions

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-core#630]
Tendermint is being actively developed and improved. We should have a plan on how to incorporate these changes after every release. Even though I would like to have a way to downstream changes from their dev branch every day(with a bot which worth investigating), I propose to strictly update this repo after every Tendermint release within a certain timeframe, like two weeks. That is, once a new release is published, maintainers of [celestia-core](https://github.com/celestiaorg/celestia-core) guarantee that within two weeks released changes from Tendermint will be incorporated. 

Initially, that might be manual labor, which later on can be automated with some bot or the bot can be used from the start.

**Comment by evan-forbes** [comment]
we've also tried a simple bot before, but there are always merge conflicts that have to handled manually, so its not much help. 

There's also the issue with reviewing PRs like that as they are usually quite large and difficult to compare the changes introduced here with the changes introduced in tendermint. This has occurred even when we pull changes every week.

**Comment by evan-forbes** [comment]
@Wondertan do you have specific changes that are needed? are they blocking? if so, I could create a branch for the version that is needed.

I finally got an updated version of master working last night in #629, and I'm almost finished with a version of the sdk that is compatible with it. While certainly not stable, the intention is to create an unstable ABCI++ version of the app so that we can start working on testnet features. Perhaps that will have the updates to tendermint that are needed?

**Comment by Wondertan** [comment]
Nothing really blocking, so no rush on this.

**Comment by evan-forbes** [comment]
> I propose to strictly update this repo after every Tendermint release within a certain timeframe, like two weeks

as we've discussed, this is a bit more involved then it seems, **but** it is reasonable to strive for as a default. In this case, I was under the impression that the sdk wouldn't have a release that used tendermint v0.35.x, and we're focusing on ABCI++ so stopped pursing this #567.

**Comment by liamsi** [comment]
>  I was under the impression that the sdk wouldn't have a release that used tendermint v0.35.x

https://github.com/cosmos/cosmos-sdk/releases/tag/v0.46.0-beta2
which uses: https://github.com/cosmos/cosmos-sdk/blob/5bde3686c4538ce53356af6e9fe40b34e4ce4a06/go.mod#L52

IMO, we should upgrade to this as soon as possible. Maybe we can already include this in testnet? Otherwise, if that is too close, we should do that for incentivized testnet (by then there actually might be an even newer release).

**Comment by liamsi** [comment]
I think we should this sooner than later. The latest with the next tagged release of the SDK. Note that this might require substantial changes to the app as well.

**Comment by evan-forbes** [comment]
can close since we've already upgraded. we might have to downgrade soon tho lol :sweat_smile:
