### ISSUE TITLE
light-client: p2p reactor

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/celestia-core#86]
Tendermint light-clients use a list of RPC nodes to talk to and to ask for "light-blocks". 
LazyLedger light-clients will operate similarly to tendermint light-client but will do DA checks though (#65). For this, they need to be able to discover and add peers. For this, we'd need a light-client related p2p reactor.

Note that the tendermint team experimented with a similar reactor (without DA checks) but [abandoned the idea](https://github.com/tendermint/tendermint/issues/4456#issuecomment-601242647) for now:
https://github.com/tendermint/tendermint/pull/4508

In this context also, we should keep an eye on the progress of the p2p-refactor: https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-061-p2p-refactor-scope.md

An alternative to using tendermint's p2p layer, could be a libp2p-based solution. This would be more work intensive but in the light of the optimint work where we will also use libp2p (cc @Wondertan @tzdybal).

**Comment by liamsi** [comment]
This enables node-type d) in the opening comment of: https://github.com/lazyledger/lazyledger-specs/issues/3

**Comment by liamsi** [comment]
@Wondertan I think here would be the right place to talk about the other idea you've mentioned yesterday: using pubsub for light-clients for the headers.

**Comment by Wondertan** [comment]
So the idea is to use [libp2p.PubSub](https://github.com/libp2p/go-libp2p-pubsub) for header broadcasting:
- Setup: Pubsub has multiple routers and for start, we can simply go with FloodSub router, which basically sends pubs to all know connection. Later on, we can go with the GossipSub router for message propagation efficiency. Also, we can omit to discover peers for now and just rely on connecting them manually. 
- Protocol: We can create a custom protocol that wraps one [pubsub.Topic](https://github.com/libp2p/go-libp2p-pubsub/blob/master/topic.go#L18) and one [pubsub.Subscription](https://github.com/libp2p/go-libp2p-pubsub/blob/master/subscription.go#L9), that simply does Header serde and pubsubing. For the topic namespace, we can come up with any suitable name, like `celestial_header_share`. In case, we need multiple places/components to listen for new Headers, we can use more than just one [pubsub.Subscription](https://github.com/libp2p/go-libp2p-pubsub/blob/master/subscription.go#L9). NOTE: It more efficient to use multiple subscriptions through code provided by PubSub's topic than wrapping one of them and implementing own multiplexing on top. NOTE2: We can omit scoring and relay concepts of pubsub for the first version of the protocol, but later on they would be very helpful.
- Usage: As discussed, we can start to use the protocol in two places. Once the block is committed in consensus, instantly publish its header to the protocol. Then light client code will receive it in the place where it processes headers instead of RPC response/subscription.

**Comment by liamsi** [comment]
Closing this as this will be implemented in https://github.com/celestiaorg/celestia-node and should be defined as part of https://github.com/celestiaorg/celestia-node/issues/1
